name: Flutter Nightly Build

on:
  # schedule:
  #   # schedule build every night
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-macos-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly" 
